// cli/beamable.templates/templates/PortalExtensionReactApp/src/lib/BeamableInit.tsx
import { useState } from 'react'
import type { Beam } from '@beamable/portal-toolkit'

interface PlayerData {
  cid: string
  pid: string
  playerId: string
}

interface BeamableInitProps {
  beam: Beam | null
}

export default function BeamableInit({ beam }: BeamableInitProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [playerData, setPlayerData] = useState<PlayerData | null>(null)

  async function init() {
    if (!beam) return
    setLoading(true)
    setError(null)
    try {
      setPlayerData({
        cid: beam.cid,
        pid: beam.pid,
        playerId: String(beam.player.id),
      })
    } catch (err) {
      console.error('Failed to init player:', err)
      setError(err instanceof Error ? err.message : String(err))
    } finally {
      setLoading(false)
    }
  }

  return (
    <beam-card>
      <div slot="actions">
        <beam-button
          onClick={init}
          disabled={loading || !!playerData ? true : undefined}
          loading={loading ? true : undefined}
        >
          {loading
            ? 'Initializing...'
            : playerData
              ? 'Player Loaded'
              : 'Initialize Player'}
        </beam-button>

        {error && <p style={{ color: 'red', marginTop: '0.5rem', fontSize: '0.9rem' }}>{error}</p>}
      </div>

      {playerData ? (
        <dl>
          <dt>CID</dt>
          <dd>{playerData.cid}</dd>
          <dt>PID</dt>
          <dd>{playerData.pid}</dd>
          <dt>Player ID</dt>
          <dd>{playerData.playerId}</dd>
        </dl>
      ) : (
        <p style={{ color: '#666', fontStyle: 'italic' }}>Click the button to load player data.</p>
      )}
    </beam-card>
  )
}

// cli/beamable.templates/templates/PortalExtensionApp/src/lib/BeamableInit.svelte
<script>
  import { Beam } from '../store.js'

  let loading = false
  let error = null
  export let playerData = null

  function init(){
    loading = true
    error = null

    try{

      playerData = {
        cid: $Beam.cid,
        pid: $Beam.pid,
        playerId: $Beam.player.id
      }
    } catch (err) {
      console.error('Failed to use Beamable SDK:', err)
      error = err.message
    } finally {
      loading = false
    }
  }

</script>

<v-card>

  <v-card-actions >
    <v-btn          
      on:click={init}
      disabled={loading || playerData ? true : null}
      loading={loading ? true : null}
    >
      {#if loading}
        Initializing...
      {:else if playerData}
        Player Loaded
      {:else}
        Initialize Player
      {/if}
    </v-btn>

    {#if error}
      <p class="error">{error}</p>
    {/if}
  </v-card-actions>

  {#if playerData}
    <portal-extension-widget 
      cid={playerData.cid}
      pid={playerData.pid}
      playerId={playerData.playerId}>
      
    </portal-extension-widget>
  {:else}
    <p class="placeholder">Click the button to load player data.</p>
  {/if}
</v-card>

<style>
  .error {
    color: red;
    margin-top: 0.5rem;
    font-size: 0.9rem;
  }

  .placeholder {
    color: #666;
    font-style: italic;
  }
</style>
