// cli/beamable.templates/templates/PortalExtensionApp/src/App.svelte
<script lang="ts">

    import {Beam, type ExtensionContext} from '@beamable/portal-toolkit'

    export let context: ExtensionContext

    let beam: Beam

    context.beam.then(b => beam = b);

</script>

<beam-card style="margin-bottom: 20px">
    <beam-card-title>
        PortalExtensionApp
    </beam-card-title>
    <beam-card-text>
        <div  style="padding: 18px">
            <div>
                Player ID {beam?.player.id}
            </div>
            <beam-btn color="primary">
                Click
            </beam-btn>
        </div>
    </beam-card-text>
</beam-card>

// cli/beamable.templates/templates/PortalExtensionReactApp/src/App.tsx
import { useEffect, useState } from 'react'
import { type Beam, type ExtensionContext } from '@beamable/portal-toolkit'

interface AppProps {
  context: ExtensionContext
}

export default function App({ context }: AppProps) {
  const [beam, setBeam] = useState<Beam | null>(null)

  useEffect(() => {
    let cancelled = false
    context.beam.then((b) => {
      if (!cancelled) setBeam(b)
    })
    return () => {
      cancelled = true
    }
  }, [context])

  return (
    <beam-card style={{ marginBottom: 20 }}>
      <h3 slot="header">PortalExtensionReactApp</h3>
      <div style={{ padding: 18 }}>
        <div>Player ID {beam?.player.id ?? '...'}</div>
        <beam-button variant="brand">Click</beam-button>
      </div>
    </beam-card>
  )
}
